# Generated by Django 4.2.24 on 2025-09-24 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the race name', max_length=200)),
                ('description', models.TextField(help_text='Describe the race, course, and any special details')),
                ('distance', models.CharField(choices=[('5K', '5K (3.1 miles)'), ('HALF', 'Half Marathon (13.1 miles)'), ('FULL', 'Full Marathon (26.2 miles)'), ('ULTRA', 'Ultra Marathon (50K+)'), ('OTHER', 'Other Distance')], default='OTHER', help_text='Select the race distance', max_length=10)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('ADULT_ONLY', 'Adult Only'), ('CRAZY_TOUGH', 'Crazy Tough'), ('EXTREMELY_FUNNY', 'Extremely Funny')], default='EASY', help_text='Select the difficulty level', max_length=20)),
                ('race_date', models.DateTimeField(help_text='Set the race start date and time')),
                ('registration_link', models.URLField(blank=True, help_text='URL to external registration page')),
                ('city', models.CharField(help_text='City name', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of race location (for map display)', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of race location (for map display)', max_digits=9, null=True)),
                ('country', models.CharField(default='UK', help_text='Country where race takes place', max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='Current race status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this race was first created')),
                ('created_by', models.ForeignKey(help_text='User who created this race', on_delete=django.db.models.deletion.CASCADE, related_name='created_races', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['race_date'],
                'indexes': [models.Index(fields=['race_date'], name='races_race_race_da_147226_idx'), models.Index(fields=['city'], name='races_race_city_7ef7a1_idx'), models.Index(fields=['status'], name='races_race_status_71cdea_idx')],
            },
        ),
    ]
