# Generated by Django 4.2.24 on 2025-09-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_alter_race_race_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='custom_distance',
            field=models.CharField(blank=True, help_text="If 'Other Distance' selected, specify the exact distance", max_length=50),
        ),
    ]
