# Generated by Django 4.2.24 on 2025-09-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_race_custom_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo for this race (optional)', null=True, upload_to='race_images/'),
        ),
        migrations.AlterField(
            model_name='race',
            name='difficulty',
            field=models.CharField(choices=[('EASY_PEASY', 'Easy-peasy'), ('ADULTS_ONLY', 'Adults Only'), ('CRAZY_TOUGH', 'Crazy Tough'), ('EXTREME_LAUGH', 'Extreme Laugh')], default='EASY_PEASY', help_text='Select the difficulty level of your crazy run', max_length=20),
        ),
    ]
