# Generated by Django 4.2.24 on 2025-09-24 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('races', '0004_race_image_alter_race_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='approved',
            field=models.BooleanField(default=False, help_text='Whether this race has been approved by admin'),
        ),
        migrations.AddField(
            model_name='race',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When this race was approved by admin', null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who approved this race', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_races', to=settings.AUTH_USER_MODEL),
        ),
    ]
