# Generated by Django 4.2.24 on 2025-09-29 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('races', '0005_race_approved_race_approved_at_race_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='Comment text (max 1000 characters)', max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='When comment was posted')),
                ('approved', models.BooleanField(default=True, help_text='Whether comment is approved for display')),
                ('author', models.ForeignKey(help_text='User who wrote this comment', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(help_text='Which race this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='races.race')),
            ],
            options={
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['race', '-created_on'], name='races_comme_race_id_2ef008_idx')],
            },
        ),
    ]
