# Generated by Django 4.2.24 on 2025-10-01 09:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='race',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a photo for this race (optional)', max_length=255, null=True, verbose_name='image'),
        ),
    ]
