# Generated by Django 4.2.24 on 2025-10-02 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('races', '0007_race_featured_image_alter_race_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text="User's reason for requesting account deletion", max_length=500)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='When the deletion was requested')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When admin reviewed the request', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When account deletion was completed', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Admin Review'), ('APPROVED', 'Approved - Account Will Be Deleted'), ('REJECTED', 'Rejected - Account Will Not Be Deleted'), ('COMPLETED', 'Completed - Account Has Been Deleted')], default='PENDING', help_text='Current status of deletion request', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes about the deletion request', max_length=500)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='User requesting account deletion', on_delete=django.db.models.deletion.CASCADE, related_name='deletion_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Deletion Request',
                'verbose_name_plural': 'Account Deletion Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
