# Generated by Django 4.2.24 on 2025-10-03 12:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0008_accountdeletionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='featured_image',
        ),
        migrations.AlterField(
            model_name='race',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', help_text='Upload a photo for this race (optional)', max_length=255, null=True, verbose_name='image'),
        ),
    ]
